laguage: node_js
cache:  
  directories:  
    - ~/.npm
node_js:
  - '12.18.0'
git:
  depth: 3
script: 
  - yarn build
deploy:
  provider: pages
  edge: true,
  skip-cleanup: true
  keep_hisory: true
  github-token: $GitHub_Token
  local-dir: dist/
  target-brach: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master